
development:
  adapter: postgresql
  encoding: unicode
  database: flab_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: flab_test
  pool: 5
  host: localhost
